### ISSUE TITLE
PFCP pcap result file does not follow rules of the PFCP protocol 

### ISSUE THREAD

**Issue by didinino** [travelping/pfcplib#1]
There can be Information Elements (=IE) that do not belong or should not be in the packet.
Each packet should follow the rules according to it's message type for each IE. the rule list: http://www.3gpp.org/ftp//Specs/archive/23_series/23.214/23214-f40.zip

*If that is not the goal of this repo, you may ignore this issue.

**Comment by RoadRunnr** [comment]
The goal of the property test that generates the content of PCAP file was not to generate proper PFCP messages, but to make sure that all valid IEs can be encoded properly.

The PCAP output was only intended to use wireshark to manually verify random IEs against wiresharks PFCP decoder.

It would be possible to enhance the generation rules to only produce messages that follow the rules, but that was not really the intention.

Why do you need a generator that produces only valid PFCP messages?

**Comment by didinino** [comment]
Thank you for the clarification, this is not an issue in that case.
I was looking for a valid pfcp pcap to test my code for the company I currently work for.

FYI: Wireshark indicates malformed packet for packets that do not follow the rules of the protocol.
